# Generated by Django 3.1 on 2020-08-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo_url', models.URLField()),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
    ]
