# Generated by Django 3.1 on 2020-08-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200819_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=100)),
                ('expires_in', models.PositiveIntegerField()),
                ('scope', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=50)),
                ('session_secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='e2c1776c31393837313031319605', max_length=50),
        ),
    ]
