# Generated by Django 3.1 on 2020-08-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200822_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
