# Generated by Django 3.1 on 2020-08-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200823_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
