# Generated by Django 3.1 on 2020-09-05 04:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200825_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='brief',
            field=ckeditor.fields.RichTextField(default='这个人很烂，没有写简介~'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_rename',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fictions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.JSONField(default={'信息': '这个人没有详细信息！'}),
        ),
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_in_date',
            field=models.DateField(default=datetime.date(2007, 8, 22)),
        ),
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default='默认用户名', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
