# Generated by Django 3.1 on 2020-09-05 04:20

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200905_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.JSONField(),
        ),
    ]
