# Generated by Django 3.1 on 2020-09-05 05:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200905_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brief',
            field=ckeditor.fields.RichTextField(default='这个人很懒，没有写简介~'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
