# Generated by Django 3.1 on 2020-09-05 05:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200905_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brief',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
