# Generated by Django 3.1 on 2020-09-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200905_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_in_date',
            field=models.DateField(),
        ),
    ]
