# Generated by Django 3.1 on 2020-09-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200905_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.JSONField(),
        ),
    ]
